
cn:
  wantedonline: this is yml test
logging:
  level:
    com.example.springbootdemo: trace
server:
  shutdown: graceful
  port: 9090
spring:
  mvc:
    static-path-pattern: static/**
    format:
      date: yyyy-MM-dd
  thymeleaf:
    cache: false
  messages:
    basename: i18n/index
  redis:
    database: 0
    host: 81.68.184.131
    port: 6379
    lettuce:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 5
        max-wait: 1ms
      shutdown-timeout: 200ms
  cache:
    cache-names: my-cache
  datasource:
    url: jdbc:mysql://81.68.184.131:3306/spring-demo-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: Rfv123!@#
    type: com.alibaba.druid.pool.DruidDataSource


wantedonline:
  name: demoApplication
  msg: hello,auto config